version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.7.8-alpine
    container_name: rabbitmq_prato
    hostname: rabbitmq_prato
    volumes:
    - ./rabbitmq:/var/lib/rabbitmq

  bot_webhook:
    build: .
    command: gunicorn webhooks.py:app --timeout 120 --log-level DEBUG -w 1 -b 0.0.0.0:8002
    volumes:
    - .:/code
    env_file:
      - .env

  worker:
    build: .
    command: celery -A chat_processor  worker --loglevel=info
    volumes:
    - .:/code
    links:
    - rabbitmq
    depends_on:
    - rabbitmq
    env_file:
      - .env

networks:
  default:
    external:
      name: pratoaberto