version: '3'

services:

  bot_webhook:
    build: .
    command: gunicorn webhooks:app --timeout 120 --log-level DEBUG -w 1 -b 0.0.0.0:8002
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - 3000:8002  # acessar localhost:8002/[facebook|telegram] para ativar o webhook

networks:
  default:
    external:
      name: pratoaberto